version: "2.0"

services:
  front:
    image: cloud_front
    container_name: cloud_front
    ports:
      - 8081:8080

  app:
    image: cloud_service:1.0
    container_name: cloud_service
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/cloud_service

  db:
    image: postgres
    container_name: cloud_db
    ports:
      - 5433:5432
    volumes:
      - ./postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: alexey
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cloud_service
